#!/bin/sh

# --------------------------------------------------
# Init launcher for: Telescope Embedded Agent (TEA).
# --------------------------------------------------

. /opt/ngat/etc/bashrc

if [ $# -ne 2 ]; then   
    target=$DEPLOY_SYSTEM
else
    target=$2
fi

# Source function library.
/etc/rc.d/init.d/functions

DAT=`date -u +"%j_%H_%M"`
TEA_CONSOLE_LOG_FILE=$DEPLOY_TMP/tea_${target}.log

$DEPLOY_ETC/log_roll $TEA_CONSOLE_LOG_FILE 4000000 5 

case "$1" in
  start)
	echo "Starting Telescope Embedded Agent for ${target}, Log to: ${TEA_CONSOLE_LOG_FILE} "
	$DEPLOY_BIN/tea start $target 1>> ${TEA_CONSOLE_LOG_FILE} 2>&1 &
	;;
  stop)
	echo "Shutting down Telescope Embedded Agent for $target."
	$DEPLOY_BIN/tea stop $target 1>> ${TEA_CONSOLE_LOG_FILE} 2>&1 
	;;
  restart)
	$0 stop	
	echo "Restarting in 30 secs"
	sleep 30
	$0 start
	;;
  *)
	echo "Usage: $0 {start | stop | restart}"
	exit 1
esac

exit 0
